# Generated by Django 3.2.16 on 2022-12-24 12:26

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KindOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind_of_work', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Тип работ',
                'verbose_name_plural': 'Типы работ',
                'ordering': ['kind_of_work'],
            },
        ),
        migrations.CreateModel(
            name='PayMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_method', models.CharField(max_length=50, unique=True, verbose_name='Тип оплаты')),
            ],
            options={
                'verbose_name': 'Тип оплаты',
                'verbose_name_plural': 'Тип оплаты',
                'ordering': ['pay_method'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
                'ordering': ['status'],
            },
        ),
        migrations.CreateModel(
            name='Loader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Отчество')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Номер телефона')),
                ('whatsapp', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True, verbose_name='Телефон для whatsapp')),
                ('photo', models.ImageField(blank=True, upload_to='photo/loader/', verbose_name='Фото')),
                ('area', models.CharField(max_length=150, verbose_name='Район проживания')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Дата приема')),
                ('first_job_date', models.DateField(blank=True, default=None, null=True, verbose_name='Дата первого выхода')),
                ('passport_serial', models.PositiveIntegerField(blank=True, null=True, verbose_name='Серия паспорта')),
                ('passport_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер паспорта')),
                ('passport_given_by', models.CharField(blank=True, help_text='Как в паспорте', max_length=200, null=True, verbose_name='Кем выдан')),
                ('passport_givendate', models.DateField(blank=True, null=True, verbose_name='Когда выдан')),
                ('passport_first_name', models.CharField(blank=True, help_text='Как в паспорте', max_length=150, null=True, verbose_name='Имя')),
                ('passport_last_name', models.CharField(blank=True, help_text='Как в паспорте', max_length=150, null=True, verbose_name='Фамилия')),
                ('passport_middle_name', models.CharField(blank=True, help_text='Как в паспорте', max_length=150, null=True, verbose_name='Отчество')),
                ('passport_birthday', models.DateField(blank=True, null=True, verbose_name='День рождения')),
                ('passport_birthplace', models.CharField(blank=True, help_text='Как в паспорте', max_length=50, null=True, verbose_name='Место рождения')),
                ('pay_requisites', models.CharField(blank=True, help_text='Номер карты/счета/телефона', max_length=150, null=True, verbose_name='Реквизиты оплаты')),
                ('bank', models.CharField(blank=True, max_length=150, null=True, verbose_name='Банк')),
                ('pay_comments', models.TextField(blank=True, max_length=500, null=True, verbose_name='Комментарии к оплате')),
                ('kind_of_work', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.kindofwork', verbose_name='Тип работ')),
                ('pay_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loaders', to='orders.paymethod', verbose_name='Тип оплаты')),
            ],
            options={
                'verbose_name': 'Грузчик',
                'verbose_name_plural': 'Грузчики',
                'ordering': ['last_name'],
            },
        ),
    ]
