# Generated by Django 3.2.16 on 2022-12-27 07:02

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactCounterAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Контактное лицо',
                'verbose_name_plural': 'Контактные лица',
            },
        ),
        migrations.CreateModel(
            name='Contactperson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=150, verbose_name='Ф.И.О')),
                ('post', models.CharField(blank=True, max_length=50, null=True, verbose_name='Должность')),
                ('email', models.EmailField(blank=True, max_length=250, null=True, verbose_name='Электронная почта')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Контактное лицо',
                'verbose_name_plural': 'Контактные лица',
            },
        ),
        migrations.CreateModel(
            name='Counteragent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Юридическое лицо', 'Юридическое лицо'), ('Физическое лицо', 'Физическое лицо')], max_length=50, verbose_name='Тип контрагента')),
                ('legal_name', models.CharField(max_length=200, unique=True, verbose_name='Юридическое наименование')),
                ('short_name', models.CharField(max_length=200, unique=True, verbose_name='Краткое наименование')),
                ('inn', models.IntegerField(blank=True, null=True, unique=True, verbose_name='ИНН')),
                ('kpp', models.IntegerField(blank=True, null=True, verbose_name='КПП')),
                ('legal_address', models.TextField(blank=True, max_length=200, null=True, verbose_name='Юридический адрес')),
                ('actual_address', models.TextField(blank=True, help_text='Оставьте пустым, если совпадает с юридическим.', max_length=200, null=True, verbose_name='Фактический адрес')),
                ('payment_account', models.IntegerField(blank=True, null=True, verbose_name='Рассчетный счёт')),
                ('correspondent_account', models.IntegerField(blank=True, null=True, verbose_name='Корреспондентский счёт')),
                ('bik', models.IntegerField(blank=True, null=True, verbose_name='БИК')),
                ('bank', models.CharField(blank=True, max_length=50, null=True, verbose_name='Наименование банка')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
                'ordering': ['short_name'],
            },
        ),
        migrations.CreateModel(
            name='KindOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind_of_work', models.CharField(max_length=50, unique=True, verbose_name='Тип работы')),
            ],
            options={
                'verbose_name': 'Тип работ',
                'verbose_name_plural': 'Типы работ',
                'ordering': ['kind_of_work'],
            },
        ),
        migrations.CreateModel(
            name='PayMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_method', models.CharField(max_length=50, unique=True, verbose_name='Тип оплаты')),
            ],
            options={
                'verbose_name': 'Тип оплаты',
                'verbose_name_plural': 'Тип оплаты',
                'ordering': ['pay_method'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, unique=True, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
                'ordering': ['status'],
            },
        ),
        migrations.CreateModel(
            name='Loader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Отчество')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Номер телефона')),
                ('whatsapp', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True, verbose_name='Телефон для whatsapp')),
                ('photo', models.ImageField(blank=True, upload_to='photo/loader/', verbose_name='Фото')),
                ('area', models.CharField(max_length=150, verbose_name='Район проживания')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Дата приема')),
                ('first_job_date', models.DateField(blank=True, default=None, null=True, verbose_name='Дата первого выхода')),
                ('passport_serial', models.PositiveIntegerField(blank=True, null=True, verbose_name='Серия паспорта')),
                ('passport_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер паспорта')),
                ('passport_given_by', models.CharField(blank=True, help_text='Как в паспорте', max_length=200, null=True, verbose_name='Кем выдан')),
                ('passport_givendate', models.DateField(blank=True, null=True, verbose_name='Когда выдан')),
                ('passport_first_name', models.CharField(blank=True, help_text='Как в паспорте', max_length=150, null=True, verbose_name='Имя')),
                ('passport_last_name', models.CharField(blank=True, help_text='Как в паспорте', max_length=150, null=True, verbose_name='Фамилия')),
                ('passport_middle_name', models.CharField(blank=True, help_text='Как в паспорте', max_length=150, null=True, verbose_name='Отчество')),
                ('passport_birthday', models.DateField(blank=True, null=True, verbose_name='День рождения')),
                ('passport_birthplace', models.CharField(blank=True, help_text='Как в паспорте', max_length=50, null=True, verbose_name='Место рождения')),
                ('passport_address', models.TextField(blank=True, max_length=200, null=True, verbose_name='Прописка')),
                ('passport_photo_main', models.ImageField(blank=True, upload_to='photo/passports/', verbose_name='Фото главной страницы')),
                ('passport_photo_address', models.ImageField(blank=True, upload_to='photo/passports/', verbose_name='Фото прописки')),
                ('pay_requisites', models.CharField(blank=True, help_text='Номер карты/счета/телефона', max_length=150, null=True, verbose_name='Реквизиты оплаты')),
                ('bank', models.CharField(blank=True, max_length=150, null=True, verbose_name='Банк')),
                ('pay_comments', models.TextField(blank=True, max_length=500, null=True, verbose_name='Комментарии к оплате')),
                ('kind_of_work', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.kindofwork', verbose_name='Тип работ')),
                ('pay_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loaders', to='orders.paymethod', verbose_name='Тип оплаты')),
            ],
            options={
                'verbose_name': 'Грузчик',
                'verbose_name_plural': 'Грузчики',
                'ordering': ['last_name'],
            },
        ),
    ]
