# Generated by Django 3.2.16 on 2022-12-20 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_loader_referer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymethod',
            options={'ordering': ['pay_method'], 'verbose_name': 'Тип оплаты', 'verbose_name_plural': 'Тип оплаты'},
        ),
    ]
