# Generated by Django 3.2.16 on 2022-12-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loader',
            name='passport_address',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Прописка'),
        ),
        migrations.AddField(
            model_name='loader',
            name='passport_photo_address',
            field=models.ImageField(blank=True, upload_to='photo/passports/', verbose_name='Фото прописки'),
        ),
        migrations.AddField(
            model_name='loader',
            name='passport_photo_main',
            field=models.ImageField(blank=True, upload_to='photo/passports/', verbose_name='Фото главной страницы'),
        ),
        migrations.AlterField(
            model_name='kindofwork',
            name='kind_of_work',
            field=models.CharField(max_length=50, unique=True, verbose_name='Тип работы'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(max_length=50, unique=True, verbose_name='Статус'),
        ),
    ]
