# Generated by Django 3.2.16 on 2022-12-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_counteragent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counteragent',
            name='actual_address',
            field=models.TextField(blank=True, help_text='Оставьте пустым, если совпадает с юридическим.', max_length=200, null=True, verbose_name='Фактический адрес'),
        ),
        migrations.AlterField(
            model_name='counteragent',
            name='bank',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Наименование банка'),
        ),
        migrations.AlterField(
            model_name='counteragent',
            name='bik',
            field=models.IntegerField(blank=True, null=True, verbose_name='БИК'),
        ),
        migrations.AlterField(
            model_name='counteragent',
            name='correspondent_account',
            field=models.IntegerField(blank=True, null=True, verbose_name='Корреспондентский счёт'),
        ),
        migrations.AlterField(
            model_name='counteragent',
            name='inn',
            field=models.IntegerField(blank=True, null=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='counteragent',
            name='kpp',
            field=models.IntegerField(blank=True, null=True, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='counteragent',
            name='legal_address',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Юридический адрес'),
        ),
        migrations.AlterField(
            model_name='counteragent',
            name='payment_account',
            field=models.IntegerField(blank=True, null=True, verbose_name='Рассчетный счёт'),
        ),
        migrations.AlterField(
            model_name='counteragent',
            name='type',
            field=models.CharField(choices=[('Юридическое лицо', 'Юридическое лицо'), ('Физическое лицо', 'Физическое лицо')], max_length=50, verbose_name='Тип контрагента'),
        ),
    ]
