# Generated by Django 3.2.16 on 2022-12-24 13:44

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20221224_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactperson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=150, verbose_name='Ф.И.О')),
                ('post', models.CharField(blank=True, max_length=50, null=True, verbose_name='Должность')),
                ('email', models.EmailField(blank=True, max_length=250, null=True, verbose_name='Электронная почта')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Контактное лицо',
                'verbose_name_plural': 'Контактные лица',
            },
        ),
        migrations.AlterField(
            model_name='counteragent',
            name='inn',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='counteragent',
            name='legal_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Юридическое наименование'),
        ),
        migrations.AlterField(
            model_name='counteragent',
            name='short_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Краткое наименование'),
        ),
        migrations.CreateModel(
            name='ContactCounterAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.contactperson', verbose_name='Контактное лицо')),
                ('counteragent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.counteragent', verbose_name='Контрагент')),
            ],
        ),
        migrations.AddField(
            model_name='counteragent',
            name='contacts',
            field=models.ManyToManyField(through='orders.ContactCounterAgent', to='orders.Contactperson', verbose_name='Контактное лицо'),
        ),
    ]
