# Generated by Django 3.2.16 on 2022-12-24 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20221224_2044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactcounteragent',
            options={'verbose_name': 'Контактное лицо', 'verbose_name_plural': 'Контактные лица'},
        ),
    ]
